import { GeistSans } from "geist/font/sans"
import { GeistMono } from 'geist/font/mono'
import localFont from 'next/font/local'
import { Toaster } from "sonner"
import "./globals.css"

const inter = localFont({
  src: [
    {
      path: '../public/fonts/InterVariable.woff2', // Adjust the path as needed
      weight: '100 900', // Define the weight range for the variable font
      style: 'normal',
    },
    {
      path: '../public/fonts/InterVariable-Italic.woff2', // Adjust the path as needed
      weight: '100 900',
      style: 'italic',
    },
  ],
  variable: '--font-inter', // Define a CSS variable name
  subsets: ["latin"],
  display: 'swap',
})

const sf = localFont({
  src: [
    {
      path: '../public/fonts/sf/SFPro.woff2',
      weight: '1 1000',
      style: 'normal',
    },
    {
      path: '../public/fonts/sf/SFProItalic.woff2',
      weight: '1 1000',
      style: 'italic',
    },
  ],
  variable: '--font-sf',
  subsets: ["latin"],
  display: 'swap',
})

export const metadata = {
  title: "AI Chatbot",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sf.variable} ${GeistMono.variable} antialiased`}>
        {children}
        <Toaster
          position="bottom-center"
          toastOptions={{
            classNames: {
              toast: "text-sm font-medium",
              success: "!bg-gray-900 !text-white !border-gray-700",
              error: "!bg-red-950 !text-red-200 !border-red-800",
              warning: "!bg-yellow-950 !text-yellow-200 !border-yellow-800",
            },
          }}
        />
      </body>
    </html>
  )
}
